[package]

name = "mathdefense"
version = "0.0.1"
authors = [ "Jack" ]
edition="2018"

[dependencies]
ggez = "*"
rand = "*"
nalgebra = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
